refactor: api_service_seperate
MinhyukK0/FastAPI_practice pull request #2
Opened 2022-01-04 09:29 UTC by MinhyukK0

## 프로젝트 디렉토리를 세분화 하였습니다.
- 기능별 api 구별
- api 와 로직이 담긴 service 분리
- black formatter를 사용하였습니다.

#### 기타사항: 커스텀에러 작성하겠습니다!

2022-01-04 12:53 UTC, Jeldo requested changes

2022-01-04 12:53 UTC, Jeldo commented on service/auth.py
> +def password_hash(password):
일반적으로 함수는 동사형으로 명명하고 있습니다.
`hash_password`가 더 적절할 것 같아요.

2022-01-04 21:43 UTC, szto requested changes

2022-01-04 21:43 UTC, szto commented on service/account.py
> +    return results
```suggestion
    return [
        {
            "id": account.id,
            "금액": account.price,
            "메모": account.memo,
            "사용자": account.user.username,
        }
        for account in accounts
    ]
```
p2: 바로 반환해 주셔도 됩니다. 굳이 변수를 할당했다가 리턴하실 필요 없습니다.

2022-01-04 21:43 UTC, szto commented on api/account.py
> +    prefix="/accounts", tags=["account"], responses={401: {"account": "invalid"}}
ask: 여기에 response 401 이 있는 건 왜 그런건가요?

2022-01-04 21:43 UTC, szto commented on api/account.py
> +async def create_account(account: Account, user: dict = Depends(get_user_by_token)):
```suggestion
async def create_account(account: Account, user: Dict = Depends(get_user_by_token)):
```
p1: type hint return type 으로 변경해 주세요~ (다른 부분도 모두요~)

2022-01-04 21:43 UTC, szto commented on api/account.py
> +    create_account_func(account.price, account.memo, user)
```suggestion
    create_account_func(price=account.price, memo=account.memo, user=user)
```
p1: 저희는 함수의 파라미터를 정의해서 넘겨주는 컨벤션을 사용하고 있어서 그렇게 모두 변경해 주세요.
그리고 func 는 모두 삭제해 주세요~ (태영님 리뷰 참조)

2022-01-04 21:43 UTC, szto commented on api/account.py
> +    return JSONResponse({"message": "CREATE_SUCCESS"}, status_code=201)
```suggestion
    return JSONResponse({"message": "CREATE_SUCCESS"}, status_code=status.HTTP_201_CREATED)
```
p2: fastapi status 패키지 통해서 정의해 주세요. 그리고 실행 시 return 을 account 로 변경해 주세요.

2022-01-04 21:43 UTC, szto commented on api/account.py
> +    return JSONResponse({"message": "CREATE_SUCCESS"}, status_code=201)
다른 부분의 status_code 도 모두 변경해 주세요.

2022-01-04 21:43 UTC, szto commented on api/user.py
> +    user_signup_func(user.username, user.email, user.password)
p2: 여기 함수 인자를 CreateUser 로 넘겨주시고 처리해 주세요.

2022-01-05 08:39 UTC, Jeldo approved these changes
선승인 드리겠습니다. 코멘트 반영해주시고 머지 부탁드릴께요.

2022-01-05 08:39 UTC, Jeldo commented on api/account.py
> +    results = read_removed_account(user=user)
P2: read_removed_account 로 반환되는 결과가 여러 account라면 read_removed_accounts 가 더 적절한 이름일 것 같아요.
get_removed_account도 같이 get_removed_accounts로 적용하면 좋을 것 같습니다.

2022-01-05 11:36 UTC, Jeldo commented
코멘트 반영해서 커밋하시는대로 채널에 핑찍어주시면 감사드릴께요. 그리고 코멘트가 이해가 안가거나 다른 의견이 있으셔도 언제든 핑찍어주시면 됩니다.

2022-01-05 11:47 UTC, MinhyukK0 commented
네 알겠습니다! :)

2022-01-05 13:27 UTC, MinhyukK0 commented on api/account.py
> +    results = read_removed_account(user=user)
단수 복수 구별하여 적용했습니다!

2022-01-05 13:31 UTC, merged